# Generated by Django 5.1.6 on 2025-02-27 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'appointment_time')},
        ),
    ]
